# -*- coding: utf-8 -*-
"""gold-portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnKnO62a-xG15uhleNbg1amdfZlfdVMj
"""

# 1. Authenticate
from google.colab import auth
auth.authenticate_user()
print('Authenticated Successfully')

# 2. Import the GBQ Library
from google.cloud import bigquery
import pandas as pd

# 3. Initialize the client with your Project ID
project_id = 'pp26-488519'
client = bigquery.Client(project=project_id)

# 4. Pull the data from SQL
sql = """
SELECT * FROM `pp26-488519.gld_price.v_gold_performance_php`
ORDER BY Market_Date DESC
"""

df = client.query(sql).to_dataframe()
df.head()

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Set Style
sns.set_theme(style="white")
fig, ax1 = plt.subplots(figsize=(12, 6))

# 2. Plot Gold Price in PHP (The Primary Y-Axis)
color_gold = '#D4AF37' # Metallic Gold color
ax1.set_xlabel('Timeline')
ax1.set_ylabel('Gold Price (PHP)', color=color_gold, fontsize=12, fontweight='bold')
sns.lineplot(data=df, x='Market_Date', y='Gold_30day_MovAVG_PHP', color=color_gold, ax=ax1, linewidth=2.5)
ax1.tick_params(axis='y', labelcolor=color_gold)

# 3. Create a second Y-axis for the S&P 500
ax2 = ax1.twinx()
color_spx = '#2E5A88' # Professional Blue
ax2.set_ylabel('S&P 500 Index', color=color_spx, fontsize=12, fontweight='bold')
sns.lineplot(data=df, x='Market_Date', y='Sp500_index', color=color_spx, ax=ax2, alpha=0.4)
ax2.tick_params(axis='y', labelcolor=color_spx)

# 4. Title and Finishing Touches
plt.title('Currency-Adjusted Gold Risk Transmission Analysis', fontsize=16, pad=20)
fig.tight_layout()

# 5. Result
plt.savefig('gold_vs_spx_analysis.png', dpi=300)
plt.show()